/** Natural example sentences for vocabulary tables */

const custom = {
  quiet: 'Please be quiet.',
  safe: 'I feel safe at home.',
  free: 'This lesson is free.',
  strong: 'You are strong.',
  weak: 'I feel weak today.',
  easy: 'This part is easy.',
  hard: 'English is hard but worth it.',
  right: 'Turn right at the door.',
  left: 'My book is on the left.',
  true: 'That is true.',
  false: 'That is false.',
  same: 'We want the same goal.',
  different: 'Every day is different.',
  important: 'English is important to me.',
  possible: 'Change is possible.',
  ready: 'I am ready to learn.',
  afraid: 'Do not be afraid to try.',
  angry: 'She is not angry.',
  calm: 'Stay calm and breathe.',
  proud: 'I am proud of you.',
  brave: 'You are brave.',
  kind: 'Be kind to yourself.',
  careful: 'Be careful online.',
  quick: 'A quick review helps.',
  slow: 'Speak slowly and clearly.',
  early: 'I wake early.',
  late: 'Sorry I am late.',
  full: 'My notebook is full.',
  empty: 'The cup is empty.',
  clean: 'Keep your space clean.',
  dirty: 'Wash dirty hands.',
  healthy: 'Healthy food helps.',
  sick: 'She is sick today.',
  pain: 'I have pain in my back.',
  doctor: 'See a doctor if needed.',
  medicine: 'Take medicine as told.',
  body: 'Move your body daily.',
  heart: 'Speak from the heart.',
  head: 'My head hurts.',
  eye: 'Close your eyes and rest.',
  hand: 'Raise your hand.',
  foot: 'My foot hurts.',
  voice: 'Use a clear voice.',
  mind: 'Keep an open mind.',
  dream: 'I dream of a good job.',
  goal: 'My goal is fluency.',
  plan: 'I plan to study tonight.',
  chance: 'Give yourself a chance.',
  change: 'Small change every day.',
  choose: 'Choose one word.',
  decide: 'I decide to continue.',
  online: 'I study online.',
  offline: 'Save lessons for offline use.',
  download: 'Download the lesson.',
  app: 'I use a learning app.',
  screen: 'Look at the screen.',
  battery: 'Charge your battery.',
  charge: 'Charge your phone.',
  click: 'Click the link.',
  search: 'Search for the word.',
  website: 'Open a safe website.',
  email: 'I check my email.',
  password: 'Never share your password.',
  video: 'Watch a short video.',
  audio: 'Listen to the audio.',
  lesson: 'Finish the lesson.',
  course: 'This course is free.',
  test: 'I take a test.',
  mistake: 'A mistake is okay.',
  correct: 'Your answer is correct.',
  practice: 'Practice every day.',
  improve: 'I improve slowly.',
  progress: 'I see progress.',
  success: 'Success takes time.',
  fail: 'If I fail, I try again.',
  win: 'We win when we learn.',
  lose: 'Do not lose hope.',
  continue: 'Continue tomorrow.',
  finish: 'Finish your homework.',
  break: 'Take a short break.',
  rest: 'Rest your eyes.',
  relax: 'Relax after study.',
  focus: 'Focus for ten minutes.',
  attention: 'Pay attention.',
  memory: 'Use memory tricks.',
  habit: 'Build a study habit.',
  routine: 'My routine is simple.',
  schedule: 'Check your schedule.',
  minute: 'Study ten minutes.',
  hour: 'One hour is enough.',
  daily: 'I study daily.',
  weekly: 'I review weekly.',
  monthly: 'Monthly check-in helps.',
  future: 'I work for my future.',
  past: 'Learn from the past.',
  present: 'Focus on the present.',
  story: 'Read a short story.',
  example: 'Give an example.',
  idea: 'That is a good idea.',
  fact: 'Check the fact.',
  reason: 'What is the reason?',
  result: 'Hard work brings results.',
  however: 'I am tired; however, I study.',
  therefore: 'I practice; therefore, I improve.',
  although: 'Although it is hard, I continue.',
  key: 'Key ideas are in the summary.',
  politics: 'We read about politics carefully.',
  God: 'People pray to God in faith.',
  yoga: 'She does yoga at home.',
  'main idea': 'What is the main idea?',
  'Wi-Fi': 'The Wi-Fi is slow.',
  URL: 'Copy the URL carefully.',
  CV: 'Update your CV.',
  percent: 'Ten percent is enough today.',
  education: 'Education opens doors.',
  knowledge: 'Knowledge grows slowly.',
  skill: 'Every skill needs practice.',
  subject: 'Grammar is my favorite subject.',
  grammar: 'Grammar takes patience.',
  vocabulary: 'I build vocabulary daily.',
  pronunciation: 'Pronunciation takes practice.',
  listening: 'Listening helps me learn.',
  speaking: 'Speaking builds confidence.',
  reading: 'Reading helps me think.',
  writing: 'Writing helps me think.',
  fluency: 'Fluency comes with time.',
  level: 'My level is beginner.',
  beginner: 'I am a beginner.',
  intermediate: 'She is intermediate now.',
  advanced: 'Advanced study comes later.',
  exam: 'The exam is next month.',
  score: 'I want a high score.',
  notebook: 'I write in my notebook.',
  dictionary: 'Use a dictionary.',
  translate: 'I translate one sentence.',
  meaning: 'What is the meaning?',
  sentence: 'Write one sentence.',
  paragraph: 'Read one paragraph.',
  topic: 'Choose a topic.',
  title: 'Read the title first.',
  summary: 'Write a short summary.',
  detail: 'Read every detail.',
  confuse: 'Do not confuse these words.',
  incorrect: 'That answer is incorrect.',
  deadline: 'I meet the deadline.',
  homework: 'I finish my homework.',
  assignment: 'The assignment is short.',
  project: 'Our project is due Friday.',
  research: 'I do research online.',
  article: 'I read one article.',
  chapter: 'Open chapter two.',
  section: 'Read this section.',
  kitchen: 'She cooks in the kitchen.',
  bathroom: 'The bathroom is clean.',
  bedroom: 'My bedroom is quiet.',
  window: 'Open the window.',
  wall: 'A map is on the wall.',
  floor: 'Sit on the floor.',
  roof: 'Rain hits the roof.',
  blanket: 'I need a warm blanket.',
  pillow: 'Fluff the pillow.',
  clothes: 'Wash your clothes.',
  dress: 'She wears a blue dress.',
  shirt: 'Iron your shirt.',
  shoes: 'Wear comfortable shoes.',
  hunger: 'I feel hunger after study.',
  thirsty: 'I am thirsty.',
  breakfast: 'I eat breakfast early.',
  lunch: 'Lunch is at noon.',
  dinner: 'We eat dinner together.',
  snack: 'A small snack is fine.',
  guest: 'Our guest is kind.',
  neighbor: 'My neighbor is helpful.',
  noise: 'Too much noise distracts me.',
  electricity: 'Electricity is expensive.',
  weather: 'The weather is cold.',
  season: 'Spring is my favorite season.',
  emotion: 'Name the emotion.',
  feeling: 'Trust your feeling.',
  mood: 'I am in a good mood.',
  joy: 'Small wins bring joy.',
  peace: 'I wish for peace.',
  shame: 'There is no shame in learning.',
  guilt: 'Do not feel guilt for resting.',
  surprise: 'What a nice surprise!',
  despair: 'Do not fall into despair.',
  courage: 'You have courage.',
  confidence: 'Confidence grows with practice.',
  shy: 'I was shy at first.',
  honest: 'Be honest with yourself.',
  patient: 'Be patient with progress.',
  impatient: 'I feel impatient sometimes.',
  rude: 'Do not be rude.',
  gentle: 'Use a gentle voice.',
  strict: 'The rule is strict.',
  serious: 'This is a serious goal.',
  funny: 'The video is funny.',
  lonely: 'I feel lonely sometimes.',
  support: 'Thank you for your support.',
  respect: 'Show respect to teachers.',
  honor: 'It is an honor to learn.',
  humble: 'Stay humble and curious.',
  grateful: 'I am grateful today.',
  thankful: 'I am thankful for you.',
  forgive: 'Forgive yourself for mistakes.',
  criticize: 'Do not criticize yourself harshly.',
  technology: 'Technology helps learners.',
  device: 'Charge your device.',
  mobile: 'I study on my mobile.',
  smartphone: 'My smartphone is old.',
  tablet: 'A tablet is easier to read on.',
  laptop: 'She saves for a laptop.',
  keyboard: 'Type on the keyboard.',
  network: 'The network is weak.',
  signal: 'I have one bar of signal.',
  storage: 'Clear storage space.',
  folder: 'Save files in one folder.',
  photo: 'Take a photo of your notes.',
  camera: 'Cover the camera for privacy.',
  privacy: 'Protect your privacy.',
  security: 'Use strong security habits.',
  scam: 'Watch for scams online.',
  comment: 'Leave a kind comment.',
  forum: 'Ask in a learning forum.',
  notification: 'Turn off notifications while studying.',
  browser: 'Open a safe browser.',
  cloud: 'Save a backup to the cloud.',
  backup: 'Back up your notes weekly.',
  I: 'I study every day.',
  you: 'You are kind.',
  he: 'He works at home.',
  she: 'She reads every day.',
  it: 'It is a good idea.',
  we: 'We learn together.',
  they: 'They help me.',
  be: 'I am fine today.',
  have: 'I have time tonight.',
  do: 'I do my best.',
  say: 'She says thank you.',
  get: 'I get messages daily.',
  make: 'We make tea together.',
  go: 'I go home after study.',
  know: 'I know her name.',
  take: 'Take your notebook.',
  see: 'I see you tomorrow.',
  come: 'Come here, please.',
  think: 'I think it is good.',
  look: 'Look at this word.',
  want: 'I want to learn English.',
  give: 'Give me one minute.',
  use: 'I use my phone to study.',
  find: 'I find new words online.',
  tell: 'Tell me your name.',
  ask: 'Ask your teacher.',
  work: 'I work from home.',
  need: 'I need more practice.',
  feel: 'I feel hopeful today.',
  try: 'I try again tomorrow.',
  call: 'Call me after class.',
  keep: 'Keep your notebook ready.',
  let: 'Let me think.',
  begin: 'Begin with five words.',
  help: 'I need help with grammar.',
  show: 'Show me the answer.',
  hear: 'I hear you clearly.',
  play: 'Children play outside.',
  run: 'She runs in the morning.',
  move: 'Move the chair, please.',
  live: 'I live in Kabul.',
  believe: 'I believe in my future.',
  bring: 'Bring water to class.',
  happen: 'Good things happen slowly.',
  write: 'Write one sentence daily.',
  sit: 'Sit and breathe.',
  stand: 'Stand up slowly.',
  pay: 'Pay attention to sounds.',
  meet: 'Nice to meet you.',
  time: 'I have time today.',
  year: 'This year I study English.',
  people: 'Many people learn online.',
  way: 'This is a good way to learn.',
  day: 'Have a good day.',
  man: 'The man is kind.',
  woman: 'The woman is a teacher.',
  child: 'The child reads a book.',
  life: 'Life is beautiful.',
  part: 'This part is easy.',
  place: 'A quiet place helps me focus.',
  world: 'The world is large.',
  home: 'I study at home.',
  house: 'Our house is small and warm.',
  room: 'I have a study room.',
  door: 'Close the door, please.',
  water: 'I need clean water.',
  food: 'The food is ready.',
  bread: 'I eat bread and tea.',
  tea: 'She drinks tea with family.',
  family: 'My family supports me.',
  mother: 'My mother works hard.',
  father: 'My father reads the news.',
  sister: 'My sister studies with me.',
  brother: 'My brother uses a phone.',
  friend: 'She is my close friend.',
  name: 'My name is Zahra.',
  country: 'I love my country.',
  city: 'The city is busy today.',
  school: 'School opens tomorrow.',
  book: 'I read one book a week.',
  phone: 'I use my phone for lessons.',
  internet: 'The internet is slow today.',
  message: 'I send a short message.',
  study: 'I study English at night.',
  student: 'I am a proud student.',
  teacher: 'The teacher speaks slowly.',
  word: 'I learn ten words a day.',
  English: 'I study American English.',
  language: 'Language opens new doors.',
  number: 'What is your phone number?',
  morning: 'Good morning, sister.',
  night: 'Good night and rest well.',
  tomorrow: 'Tomorrow I start early.',
  yesterday: 'Yesterday I was tired.',
  week: 'This week I practice speaking.',
  month: 'Next month I take a quiz.',
  please: 'Please help me.',
  thank: 'I thank you from my heart.',
  sorry: 'I am sorry I was late.',
  excuse: 'Excuse me, may I ask?',
  hello: 'Hello, how are you?',
  goodbye: 'Goodbye for now.',
  welcome: 'You are welcome here.',
  problem: 'I have a small problem.',
  question: 'I have one question.',
  answer: 'Please answer slowly.',
  open: 'Open your notebook.',
  close: 'Close the window at night.',
  remember: 'Remember to review.',
  forget: 'Do not forget to rest.',
  understand: 'I understand a little.',
  hope: 'I hope for a peaceful future.',
  love: 'I love my family.',
  like: 'I like quiet mornings.',
  eat: 'I eat breakfast at seven.',
  drink: 'I drink water often.',
  sleep: 'I sleep at ten o\'clock.',
  wake: 'I wake up at six.',
  wash: 'I wash my hands first.',
  cook: 'She cooks rice and beans.',
  walk: 'I walk after dinner.',
  and: 'Tea and bread are enough.',
  but: 'I am tired, but I study.',
  or: 'Tea or water?',
  because: 'I study because I want a job.',
  so: 'I was confused, so I asked.',
  if: 'If you can, practice aloud.',
  when: 'When I finish, I rest.',
  where: 'Where is your notebook?',
  what: 'What is this word?',
  who: 'Who is your teacher?',
  why: 'Why English? For my future.',
  how: 'How do you say this?',
  in: 'I am in my room.',
  on: 'The book is on the table.',
  at: 'I study at night.',
  to: 'I go to the lesson.',
  from: 'I am from Afghanistan.',
  with: 'I study with my sister.',
  without: 'Without internet, I use offline files.',
  for: 'This notebook is for you.',
  of: 'A cup of tea, please.',
  about: 'Tell me about your day.',
  up: 'Stand up, please.',
  down: 'Sit down and breathe.',
  here: 'Come here.',
  there: 'Your phone is over there.',
  now: 'I study now.',
  then: 'First listen, then repeat.',
  very: 'Very good work today!',
  too: 'It is too noisy here.',
  also: 'I also write in English.',
  only: 'Only fifteen minutes today.',
  not: 'I am not giving up.',
  all: 'All my sisters study.',
  some: 'I have some free time.',
  many: 'Many women learn English.',
  few: 'I know a few words.',
  more: 'I need more listening practice.',
  less: 'Less fear, more practice.',
  first: 'First, read the word.',
  last: 'This is the last exercise.',
  next: 'Next week I start Module 5.',
  before: 'Wash hands before eating.',
  after: 'After study, I rest.',
  again: 'Say it again, please.',
  always: 'I always try my best.',
  never: 'I never stop learning.',
  sometimes: 'Sometimes I study with friends.',
  often: 'I often study at night.',
  usually: 'I usually study for thirty minutes.',
  today: 'Today I learn ten new words.',
  together: 'We study together.',
  alone: 'Sometimes I study alone.',
  interview: 'I practice for the interview.',
  volunteer: 'I volunteer at school.',
  certificate: 'I want a certificate.',
  scholarship: 'She hopes for a scholarship.',
  mentor: 'My mentor encourages me.',
};

const prepEx = {
  in: 'I am in my room.',
  on: 'The book is on the table.',
  at: 'I study at night.',
  to: 'I go to class.',
  from: 'I am from Afghanistan.',
  with: 'I study with my sister.',
  without: 'Without Wi-Fi, I use offline files.',
  for: 'This is for you.',
  of: 'A cup of tea, please.',
  about: 'Tell me about your day.',
  up: 'Stand up, please.',
  down: 'Sit down.',
  here: 'Come here.',
  there: 'It is over there.',
  near: 'The school is near my home.',
  under: 'The bag is under the table.',
  over: 'The lamp is over the desk.',
  into: 'Go into the lesson.',
  through: 'Read through the page.',
  during: 'During study, silence helps.',
  before: 'Read before you write.',
  after: 'Rest after you study.',
  between: 'Choose between two answers.',
  among: 'She is among her friends.',
  above: 'The light is above the desk.',
  across: 'Walk across the room.',
  against: 'Do not lean against the wall.',
  along: 'Walk along the street.',
  around: 'Look around the room.',
  away: 'Put the phone away.',
  back: 'Come back tomorrow.',
  behind: 'The chair is behind the table.',
  below: 'The answer is below.',
  beneath: 'The box is beneath the bed.',
  beside: 'Sit beside your sister.',
  beyond: 'Go beyond your fear.',
  except: 'Everyone came except Ali.',
  inside: 'Stay inside when it rains.',
  onto: 'Put the book onto the table.',
  out: 'Go out for fresh air.',
  outside: 'Wait outside the door.',
  past: 'Walk past the market.',
  since: 'I have studied since January.',
  throughout: 'Smile throughout the day.',
  toward: 'Work toward your goal.',
  until: 'Study until you are tired.',
  upon: 'Once upon a time, she learned.',
  within: 'Finish within ten minutes.',
};

const conjEx = {
  and: 'Bread and tea.',
  but: 'Small but strong.',
  or: 'Now or later?',
  because: 'I study because I want work.',
  so: 'I was tired, so I rested.',
  if: 'If you can, help me.',
  when: 'When I finish, I call you.',
  where: 'Where is the class?',
  what: 'What is your name?',
  who: 'Who is she?',
  why: 'Why English? For my future.',
  how: 'How do you say this?',
  although: 'Although I am tired, I study.',
  though: 'Though it is hard, I continue.',
  unless: 'Do not stop unless you must.',
  while: 'While I cook, I listen.',
  whereas: 'She reads, whereas I write.',
};

const advEx = {
  very: 'Very good!',
  too: 'It is too hot.',
  also: 'I also like music.',
  only: 'Only ten minutes.',
  not: 'I am not late.',
  again: 'Try again.',
  always: 'I always try.',
  never: 'I never give up.',
  sometimes: 'Sometimes I am tired.',
  often: 'I often study at night.',
  usually: 'I usually study at six.',
  today: 'Today I learn ten words.',
  together: 'We study together.',
  alone: 'Sometimes I study alone.',
  now: 'I study now.',
  then: 'First read, then write.',
  already: 'I already reviewed.',
  almost: 'I almost finished.',
  enough: 'That is enough.',
  even: 'Even five minutes helps.',
  just: 'I just started.',
  maybe: 'Maybe tomorrow.',
  perhaps: 'Perhaps she is busy.',
  quite: 'Quite good!',
  rather: 'I would rather study.',
  still: 'I am still learning.',
  which: 'Which word is new?',
  whose: 'Whose notebook is this?',
  whom: 'To whom did you speak?',
};

const irregular = {
  be: 'I am fine today.',
  have: 'I have time tonight.',
  do: 'I do my best.',
  go: 'I go home after study.',
  say: 'She says thank you.',
  get: 'I get messages daily.',
  make: 'We make tea together.',
  know: 'I know her name.',
  take: 'Take your notebook.',
  see: 'I see you tomorrow.',
  come: 'Come here, please.',
  think: 'I think it is good.',
  give: 'Give me one minute.',
  find: 'I find new words online.',
  tell: 'Tell me your name.',
  ask: 'Ask your teacher.',
  keep: 'Keep studying.',
  let: 'Let me think.',
  begin: 'Begin today.',
  hear: 'I hear you clearly.',
  run: 'She runs in the morning.',
  write: 'Write one sentence daily.',
  sit: 'Sit and breathe.',
  stand: 'Stand up slowly.',
  lose: 'Do not lose hope.',
  pay: 'Pay attention.',
  meet: 'Nice to meet you.',
  read: 'I read every day.',
  speak: 'I speak slowly.',
  learn: 'I learn English.',
  teach: 'She teaches online.',
  eat: 'I eat breakfast at seven.',
  drink: 'I drink water often.',
  sleep: 'I sleep at ten.',
  wake: 'I wake at six.',
  wash: 'I wash my hands.',
  cook: 'She cooks rice.',
  walk: 'I walk after dinner.',
  send: 'I send a message.',
  buy: 'I buy fruit at the market.',
  sell: 'They sell fresh bread.',
  build: 'We build skills slowly.',
  break: 'Take a break.',
  choose: 'Choose one word.',
  decide: 'I decide to continue.',
  bring: 'Bring your notebook.',
  hold: 'Hold the phone with both hands.',
  open: 'Open the book.',
  close: 'Close the door.',
  listen: 'Listen carefully.',
  watch: 'Watch the short video.',
  wait: 'Wait, please.',
  try: 'I try again tomorrow.',
  start: 'I start at six.',
  stop: 'Please stop talking.',
  help: 'I need help.',
  work: 'I work from home.',
  live: 'I live in Kabul.',
  love: 'I love my family.',
  like: 'I like quiet study time.',
  want: 'I want to learn English.',
  need: 'I need more practice.',
  use: 'I use my phone to study.',
  call: 'Call me later.',
  play: 'Children play outside.',
  move: 'Move the chair.',
  feel: 'I feel calm today.',
  happen: 'It happens step by step.',
  mean: 'What does this word mean?',
  leave: 'I leave at five.',
  put: 'Put it here.',
  set: 'Set a small daily goal.',
  show: 'Show me the word.',
  follow: 'Follow the lesson steps.',
  turn: 'Turn the page.',
  grow: 'Your skills grow daily.',
  sing: 'She sings softly.',
  throw: 'Do not throw your phone.',
  catch: 'Catch the main idea.',
  fight: 'Fight for your dreams.',
  win: 'You win when you try.',
  fail: 'If I fail, I try again.',
  pass: 'I pass the unit quiz.',
};

const verbSet = new Set([
  'accept', 'achieve', 'affect', 'allow', 'avoid', 'base', 'beat', 'become', 'check',
  'claim', 'collect', 'compare', 'complete', 'connect', 'consider', 'create', 'describe',
  'develop', 'discover', 'discuss', 'draw', 'drive', 'drop', 'expect', 'explain', 'express',
  'fall', 'fill', 'finish', 'force', 'form', 'gain', 'include', 'increase', 'indicate',
  'involve', 'join', 'lead', 'offer', 'order', 'pick', 'place', 'point', 'prepare',
  'present', 'produce', 'provide', 'raise', 'reach', 'realize', 'receive', 'reduce', 'refer',
  'relate', 'remain', 'remove', 'report', 'represent', 'require', 'return', 'reveal', 'rise',
  'save', 'seek', 'seem', 'serve', 'share', 'shut', 'spend', 'stay', 'succeed', 'suffer',
  'suggest', 'support', 'talk', 'tend', 'visit', 'warn', 'wish', 'wonder', 'worry',
  'analyze', 'contrast', 'define', 'paraphrase', 'quote', 'summarize', 'introduce', 'conclude',
  'argue', 'refute', 'oppose', 'assume', 'suppose', 'predict', 'imply', 'appear', 'hire',
  'fire', 'quit', 'apply', 'negotiate', 'cooperate', 'manage', 'organize', 'celebrate',
  'donate', 'volunteer', 'interpret', 'block', 'install', 'uninstall', 'login', 'logout',
  'subscribe', 'notify', 'edit', 'update', 'delete', 'copy', 'paste', 'record', 'pause',
  'invite', 'wear', 'dry', 'recover', 'protect', 'hurt', 'breathe', 'stretch', 'forgive',
  'miss', 'enjoy', 'comfort', 'encourage', 'discourage', 'motivate', 'inspire', 'admire',
  'praise', 'blame', 'prefer', 'hate', 'trust', 'doubt', 'repeat', 'review', 'achieve',
  'hire', 'negotiate', 'cooperate', 'lead', 'manage', 'organize', 'celebrate', 'donate',
]);

export function example(word) {
  const key = word.toLowerCase();
  if (custom[key] || custom[word]) return custom[key] || custom[word];
  if (prepEx[key]) return prepEx[key];
  if (conjEx[key]) return conjEx[key];
  if (advEx[key]) return advEx[key];
  if (irregular[key]) return irregular[key];

  const w = key;
  const cap = word.charAt(0).toUpperCase() + word.slice(1);

  if (w.endsWith('ly') && w.length > 4) return `She speaks ${w}.`;
  if (w.endsWith('ing')) return `${cap} takes practice.`;
  if (w.endsWith('tion') || w.endsWith('sion')) return `${cap} helps me learn.`;
  if (w.endsWith('ment')) return `${cap} takes time.`;
  if (w.endsWith('ness')) return `I feel ${w}.`;
  if (w.endsWith('ful')) return `That is ${w}.`;
  if (w.endsWith('less')) return `It feels ${w}.`;
  if (w.endsWith('ous') || w.endsWith('ive') || w.endsWith('al') || w.endsWith('ic'))
    return `This lesson is ${w}.`;
  if (w.endsWith('ed')) return `I feel ${w}.`;
  if (w.endsWith('er') || w.endsWith('or')) return `The ${w} helps me.`;

  if (verbSet.has(w)) {
    if (w.endsWith('e')) return `I ${w} every day.`;
    return `I ${w} with care.`;
  }

  if (w.startsWith('un') && w.length > 4) return `It is ${w}.`;
  if (w.endsWith('able')) return `You are ${w} to learn.`;
  if (w.endsWith('ous') || w.endsWith('ive') || w.endsWith('al') || w.endsWith('ic'))
    return `This is a ${w} topic.`;
  if (w.endsWith('ed')) return `I feel ${w}.`;
  if (w.endsWith('ly')) return `She speaks ${w}.`;

  if (w.length <= 5) return `I use "${w}" in a sentence.`;
  return `This word is ${w}.`;
}
